# Description:
#   Korlin port of Brotli decoder.

load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT

kt_jvm_library(
    name = "dec",
    srcs = [
        "BrotliInputSource.kt",
        "Decode.kt",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_jetbrains_kotlinx_kotlinx_io_core_jvm",
    ],
)

kt_jvm_library(
    name = "test_compat",
    srcs = ["BrotliInputStreamCompat.kt"],
    visibility = ["//visibility:public"],
    deps = [
        ":dec",
        "@maven//:org_jetbrains_kotlinx_kotlinx_io_core_jvm",
    ],
)
